### ISSUE TITLE
Rebass styles not applied on first load 

### ISSUE THREAD

**Issue by iammatthias** [iammatthias/.com#59]
Rebass media queries are not applied correctly after site is built and published on Netlify. Styles behave properly in local development. 

## Steps to Reproduce
1. Clear cache and reload page https://iammatthias.com (Shift + Command + R)
2. Page will present incorrectly 
3. After page refresh, content loads as expected 
4. If content does not load correctly after refresh, try again. It can take 3-4 attempts. 

## References: 
- https://github.com/gatsbyjs/gatsby/issues/6413
- https://github.com/gatsbyjs/gatsby/issues/13966
- https://github.com/gatsbyjs/gatsby/issues/7376

## Proposed Solutions
- Install `gatsby-plugin-styled-components` and add to GatsbyJS config
  - Already installed, no change
- Reevaluate Global styles (https://github.com/gatsbyjs/gatsby/issues/13966#issuecomment-491364273)
- ?

### Expected 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5431737/57544144-563a3300-730b-11e9-856d-01a84e5b7011.png">

### Result
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5431737/57544136-4f132500-730b-11e9-92f4-9ff923eb5e60.png">

**Comment by wiput1999** [comment]
Hmmmm I'm facing the same here

**Comment by iammatthias** [comment]
```
import Layout from './src/components/general/Layout'

export const wrapPageElement = ({ element, props }) => {
  return <Layout {...props}>{element}</Layout>
}
```

Got removed from [gatsby-browser](https://github.com/iammatthias/.com/blob/master/gatsby-browser.js) and [gatsby-ssr](https://github.com/iammatthias/.com/blob/master/gatsby-ssr.js). Added the above snippet, and all is well.
