### ISSUE TITLE
Hard forking - netlify build fail

### ISSUE THREAD

**Issue by le-dawg** [iammatthias/.com#72]
Hi, 

I attempted to deploy a fork to netlify adn that failed due to netlify not correctly parson the toml 

`no build script found, proceeding to deployment`

I manually added the (of course present) build instructions from the package.json only to find the process to fail due to

`Error: Contentful space ID and access token need to be provided.`

Which of course makes sense - or does it? 

Is it possible to create a netlify-deployable repo that doesn't leak your contentful credentials?
OTOH: is leaking those credentials a risk since they do not present the opportunity to write content into your content model?

**Comment by iammatthias** [comment]
It might be possible, but I'm not interested in doing that. The code is open source, you're free to take a look at how it is built, but the site itself is under **copyright**. It's my personal portfolio, and a lot of work went into it. 

There are plenty of MIT licensed starters available that you can use as a basis to build something similar. I suggest this one, if you want to use Contentful: https://github.com/ryanwiemer/gatsby-starter-gcn
